capabilities:
  browserName: "chrome"
  goog:chromeOptions:
    binary: /usr/bin/google-chrome-stable
    args:
      - no-sandbox
      - disable-dev-shm-usage
      - headless
      - nogpu
output-directory: results
output-format: junit